%(
	:auth<finanalyst>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:generated<template-raku>,
	:jquery-lib<https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js>,
	:license<Artistic-2.0>,
	:render<js-collator.raku>,
	:template-raku<js-templates.raku>,
	:version<0.1.0>,
)