#!/usr/bin/env bash
if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi
echo lib/plugins/html/$1
if [ -d lib/plugins/html/$1/scss ];
then
    sass --update --no-source-map lib/plugins/html/$1/scss:lib/plugins/html/$1/css
else
    sass --update --no-source-map lib/plugins/html/$1:lib/plugins/html/$1
fi