%(
	:auth<finanalyst>,
	:authors(
		"finanalyst",
	),
	:custom-raku(),
	:generated<template-raku>,
	:license<Artistic-2.0>,
	:render<css-collator.raku>,
	:template-raku<css-templates.raku>,
	:transfer<cleanup.raku>,
	:version<0.1.0>,
)